name: Dicom-Decomp
channels:
  - intel
  - conda-forge
  - anaconda
dependencies:
- numpy
- scikit-image
- progressbar2 
- pydicom
- joblib
- natsort
- pillow
- gdcm
- matplotlib
- openjpeg
- jpeg
- joblib


  
